spring:
  application:
    name: spring-boot-trpc-server

logging:
  level:
    root: info

trpc:
  server:
    port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:8761/eureka/,http://127.0.0.1:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30
